### ISSUE TITLE
Improving the Font and UI of the Website

### ISSUE THREAD

**Issue by gautamjajoo** [BRL-CAD/web#18]
Here's a suggestion of Improving the Font and UI of the Website. @brlcad 
The Expected Behaviour is 
![capture](https://user-images.githubusercontent.com/24366008/31395030-6a4825de-adfd-11e7-8b9a-cbf561c204f6.JPG)

**Comment by sniok** [comment]
Changing font is quite a subjective improvement. 

And what UI changes are present in the screenshot?

**Comment by gautamjajoo** [comment]
The whole bottom of the Solid Modelling moves when we hover over the Solid Modelling!!
Expected Behaviour
Only that section should move rather than whole bottom page..

**Comment by utkarshsingh341** [comment]
I wrote all of this code in GCI 2014. Give me some credit man!!

**Comment by brlcad** [comment]
@utkarshsingh341 , definitely will be doing that -- the new website is technically still unannounced so we've not been able to credit the authors that helped bring it all together (yourself included).  The last piece is getting mediawiki styling updated (which is beta in a separate repo).  The final result is a mashup of ideas from about 6 different people, but the overarching design is a pretty satisfying culmination of effort.  Kudos.

@gautamjajoo , do you see the hovering issue on the live website (brlcad.org) or just on a checkout?  I definitely like the menu over what's at beta.brlcad.org but still like brlcad.org with the center logo placement best myself (other devs have different opinions on this point).
