### ISSUE TITLE
Deploying the website to reflect changes in https://brlcad.org/

### ISSUE THREAD

**Issue by DamianArado** [BRL-CAD/web#63]
Please look into the pull request `Fixes in index page #62` and deploy after testing the working of website locally.

**Comment by brlcad** [comment]
Thank you @DamianArado!  Little backlogged after the holidays, but your pull request will get merged.  Thank you again!

**Comment by DamianArado** [comment]
Sir, please look into the pull request 
https://github.com/BRL-CAD/web/pull/62
I don't think there will be any problem, please let me know if something's
wrong! 😀
